#---
server:
  port: 8888
security:
  basic:
    enabled: false
  user:
    name: user
    password: pass
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls
          search-paths:
            - 'station*'   
management:
  security:
    enabled: false
