#---
server:
  port: 8888
security:
  basic:
    enabled: false
  user:
    name: user
    password: pass
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IMinchevQA/java-microservices-with-spring-cloud
          search-paths:
            - 'station*'   
management:
  security:
    enabled: false
